### ISSUE TITLE
Bad camera connection can mess up camera view menus

### ISSUE THREAD

**Issue by mickp** [MicronOxford/cockpit#10]
If cockpit can't connect, clicking in the camera name area of the Camera Views window throws an error to StdErr about having no menu item.

**Comment by iandobbie** [comment]
Works better but still a few strange responses. 
1) Turning off the camera generates an error, which doesn't recover unless the remote is restarted.
2) killing the remote leave the camera as "Busy" if you try to disconnect. This doesn't recover unless the main cockpit program is restarted.

**Comment by mickp** [comment]
1) Probably depends on the camera - I remember one camera needed all processes that use its DLL killed and restarted before the DLL your re-enumerate the camera.

2) Not surprising. If the remote is restarted, it has no idea where it should be sending status or data to. We probably need a timeout in cockpit so the button goes to the error state, which means you can then try and reconnect again.

**Comment by mickp** [comment]
Fixed in 502f27c066a5f22571ee42690c27a64c28fd1d57..768f7311797700d4f6bceb239b64e5044cd8d0bd.
