### ISSUE TITLE
Non-simultaneous multi-channel acquisition doesn't work properly. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#215]
Trying to get no simultaneous images at diamond leads to complete saturation in the green from the 561 laser. I think that it isn't properly waiting for acquisition on one channel o finish before the second starts.

**Comment by mickp** [comment]
Needs testing on CryoSIM - probably due to shutter lag on the 561,

**Comment by iandobbie** [comment]
Tested extensively at Diamond. This is no longer a problem.
