### ISSUE TITLE
Touchscreen updates

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#277]
1) Changing the Z stage from coarse to fine doesn't update the touchscreen step size etc...
2) Mick's richardproof code doesnt allow steps down, only up!
3) Touchscreen Z step controls are wrongly positioned

**Comment by iandobbie** [comment]
All fixed now

**Comment by carandraug** [comment]
For future reference, those were fixed with pull request #376 and commit dec9850eed4e0be
