### ISSUE TITLE
Turning off laser while in video mode crashes cockpit.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#283]
Seems to be reproducible, turning of a light source, either laser or ambient, while in video mode kills cockpit.

**Comment by iandobbie** [comment]
Tested on DeepSIM and it works fine. Need to confirm on CryoSIM.

**Comment by mickp** [comment]
Was this something we only ever saw on CryoSIM, or was it equally frequent on DeepSIM and CryoSIM? In the latter case, we should just close it, as it's already been tested.

**Comment by iandobbie** [comment]
Sorry I can’t remember. We definitely first noticed it on CryoSIM. It was with the pre microscope laser control.

Ian

Sent from my iPhone

On 12 Jul 2018, at 12:56, Mick <notifications@github.com<mailto:notifications@github.com>> wrote:


Was this something we only ever saw on CryoSIM, or was it equally frequent on DeepSIM and CryoSIM? In the latter case, we should just close it, as it's already been tested.

**Comment by iandobbie** [comment]
Now fixed. Turning off the last light source stops video mode.
