### ISSUE TITLE
Issues arrising at CryoSIM commissioning.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#288]
After 3 days working continuously at CryoSIM there are a few glaring issues that would help usability a lot. 

1) Be able to take a transmission snapshot with a SIM experiment. just turn on the transmission LED and light control, snap a single image in the centre of the stack and store under some obvious name. revert light controls and run the configured experiment. 

2) Metadata storage. We need to add excitation wavelengths so we can do recosntructions with different stripe widths.

3) warn if you are about to start an experiment with a trigger on a light but the light source off. 

4) Fans on cameras should be turned off when water cooling is  on, and not just on camera enable, which can mean that although water cooling in enabled the fan is still on high speed. 

5) Ability to store a quick snap image into a file

6) Timer since last fill so you can decide weather to start and experiment or not.

**Comment by iandobbie** [comment]
part 2 fixed by Davids meta data updates

**Comment by iandobbie** [comment]
issue 4 might be fixed in my camera_cooling branch, needs testing

**Comment by iandobbie** [comment]
point 4 fixed in #370

**Comment by iandobbie** [comment]
point 1 is a duplicate of #284. this only leaves points 3 and  5

**Comment by mickp** [comment]
Opened #390 and #391 for 3. and 5.
