### ISSUE TITLE
Users are fundamentally broken.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#293]
You can login as a user but not logout. Also you cannot get the data stored in a sub directory on collection so all the data is mixed together. 

We should enable some mechanism for storing data in sub directories. 

Having to shutdown to logout of a user is also a bit crap!

**Comment by mickp** [comment]
Should look at ditching our own user logins and use the system login instead. We may be able to repurpose this for different measurement configs, though.

**Comment by carandraug** [comment]
As we discussed in person, we will be removing the whole user management from cockpit and rely on the OS to do that part. Related to this is issue #320 , about the default config directories.  The default config directories are being changed to be configurable and user (from the OS) dependent.

On the topic of reusing the user login to select multiple configuration, we decided not to do it, at least not for now. Currently, configuration works by reading all conf files in a specific directory and merge them all together. There's currently no method to have multiple configurations around and get cockpit to pick a specific. So maybe in the future.

**Comment by carandraug** [comment]
I have removed the whole user management from cockpit. The work is kinda mixed with the changes to the default config directories (still separate commits).  Can someone take a look at my `config-dirs` branch?

```
git fetch david
git checkout david/config-dirs
```

Or in the web interface, the comparison and individual commits with [master..config-dirs](https://github.com/carandraug/cockpit/compare/master..config-dirs)

**Comment by mickp** [comment]
I have some suggested changes at mickp/cockpit/config-dirs . 
I can't create a pull request against carandraug/cockput because that fork is detached from all the others (probably from when we made the repo public). Can you please rebind your fork to MicronOxford/cockpit, so that it shows up in the fork list and can GitHub interface for pull requests?

**Comment by carandraug** [comment]
Thanks for the review. I have pushed it now together with your changes. This closes the issue, there are no more cockpit users.

About my cockpit clone repo not being linked, I will make a new github clone linked to this after I finish the experiment frame rework. Thing is, I'm constantly rewriting the history on my own branches but I also reference issues numbers. So we'll fill the issues with many notifications about commits that disappear after a few days.
