### ISSUE TITLE
Aerotech lifter timeout problem.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#300]
Sometimes when running an experiment on DeepSIM the experiment fails to start as the aerotech lifter still thinks its moving. Not exactly sure what causes this, and its not frequent but still a pretty frustrating bug. 

swapping to the aerotech stage, moving it and then refocusing and restart typically fixes this issue.

**Comment by mickp** [comment]
This is probably mechanical - the stage is not quite reaching its set point.
