### ISSUE TITLE
Trap errors on startup

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#307]
If there is a problem on startup, say a laser remote not running, then cockpit dies with horribly opaque errors. We need to do something like a try/except around all connections and either stop with a sensible error or disable that device.

**Comment by mickp** [comment]
I think this was fixed because of a bug: there was cleanup code to be run after App.mainloop() exited, but it was never hit because the main loop was started by a modal dialog box before App.mainloop() was reached.
