### ISSUE TITLE
sort out license for cockpit

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#308]
We got permission from UCSF to use cockpit under the 3 clause BSD license.  Our own modifications are under GPLv3+.  At the moment we got both licenses at the root of the project but we need to put the right license headers in the appropriate files.  I went through the history and prepared a commit to do this.

Here's the list of current files in cockpit each of us has modified.  I have placed your names in those files as copyright holders.  Let me know if you think you should be added to any other file, or you want your name or email in some other form:

* @tomparks 
  * `experiment/sweptShutter.py`
  * `gui/loggingWindow.py`
  * `handlers/stagePositioner.py`
* @langefj 
  * `gui/mosaic/window.py`
* @NickHallONBI 
  * `devices/windowsUSBJoystick.py`
  * `interfaces/stageMover.py`
* @juliomateoslangerak 
  * `cockpit.pyw`
  * `devices/camera.py`
  * `devices/ni_cRIOFPGA.py`
  * `experiment/experiment.py`
  * `gui/macroStage/macroStageZ.py`
  * `handlers/camera.py`
  * `util/connection.py`
* @iandobbie 
  * `cockpit.pyw`
  * `devices/aerotechAxis.py`
  * `devices/andorCameras.py`
  * `devices/boulderSLM.py`
  * `devices/configurator.py`
  * `devices/nanomover.py`
  * `devices/ni6036e.py`
  * `devices/objective.py`
  * `devices/physikInstrumenteM687.py`
  * `devices/picomotor.py`
  * `devices/piDIO.py`
  * `devices/polarizationRotator.py`
  * `devices/softCamera.py`
  * `devices/windowsUSBJoystick.py`
  * `experiment/dataSaver.py`
  * `experiment/optoScriptExample.py`
  * `experiment/structuredIllumination.py`
  * `experiment/stutteredZStack.py`
  * `gui/adminWindow.py`
  * `gui/camera/viewPanel.py`
  * `gui/device.py`
  * `gui/dialogs/enumerateSitesPanel.py`
  * `gui/dialogs/experiment/experimentConfigPanel.py`
  * `gui/dialogs/experiment/multiSiteExperiment.py`
  * `gui/dialogs/experiment/singleSiteExperiment.py`
  * `gui/dialogs/getNumberDialog.py`
  * `gui/dialogs/offsetSitesDialog.py`
  * `gui/dialogs/safetyMinDialog.py`
  * `gui/drawShapes.py`
  * `gui/guiUtils.py`
  * `gui/imageViewer/viewCanvas.py`
  * `gui/keyboard.py`
  * `gui/loggingWindow.py`
  * `gui/macroStage/macroStageBase.py`
  * `gui/macroStage/macroStageWindow.py`
  * `gui/macroStage/macroStageXY.py`
  * `gui/macroStage/macroStageZ.py`
  * `gui/mainWindow.py`
  * `gui/mosaic/canvas.py`
  * `gui/mosaic/window.py`
  * `gui/saveTopBottomPanel.py`
  * `gui/toggleButton.py`
  * `gui/touchscreen/slavecanvas.py`
  * `gui/touchscreen/slaveMacroStageZ.py`
  * `gui/touchscreen/slaveOverview.py`
  * `gui/touchscreen/touchscreen.py`
  * `gui/valueLogger.py`
  * `handlers/lightPower.py`
  * `handlers/lightSource.py`
  * `handlers/objective.py`
  * `interfaces/stageMover.py`
  * `interfaces/valueLogger.py`
  * `util/intensity.py`
* @carandraug
  * `cockpit.pyw`
  * `experiment/dataSaver.py`
  * `experiment/structuredIllumination.py`
  * `gui/imageViewer/viewCanvas.py`
  * `gui/loggingWindow.py`
  * `gui/mosaic/canvas.py`
  * `handlers/deviceHandler.py`
  * `handlers/executor.py`
  * `util/datadoc.py`
  * `util/ftgl.py`
  * `util/Mrc.py`

@mickp , in your case it's easier to list the files you haven't touched:
* `gui/progressDialog.py`
* `gui/shellWindow.py`
* `interfaces/__init__.py`
* `util/importer.py`
* `util/logger.py`
* `util/profile.py`
* `util/threads.py`

# How the commit was prepared

Get list of people who did something in cockpit:

```
$ cut -f2 <(git shortlog --committer --summary) <(git shortlog --summary) | sort -u > authors-list
$ cat authors-list
Carnë Draug
David Pinto
Derakon
Eric Branlund
GitHub
Ian Dobbie
Julio Mateos Langerak
langefj
map
Mick
mickp
Mick Phillips
NickHall
Thomas Parks
tomparks
unknown
```

From this list, the weirdly named authors are:

* map is Mick Phillips
* unknown is Mick Phillips (`vga83285@B24-AXIOIMAGER.dc.diamond.ac.uk` and `<whgu0532@bioch3152.bioch.ox.ac.uk>`)
* GitHub are merge commits
* Derakon is Chris Weisiger
* Carnë Draug is David Pinto
* langefj is Rick Lange
* tomparks is Thomas Parks

## List all files

Include only python file and ignore the config stuff and the testsuite (David wrote the files in the testsuite and they already have a license):

```
find -type f -not -empty -regex '.*pyw?' \
  -not -path './testsuite/*' \
  -not -path './config/*' \
  -not -path './sample-configs/*' \
  | sed 's,^\./,,' | sort -u > all-files
```

## List files from UCSF

All UCSF commits are from Eric Branlund and Derakon (Chris Weisiger)

```
git log --no-merges \
  --author="Derakon" --author="Eric Branlund" \
  --name-only --pretty=format:"" | sort -u | grep -P '\.pyw?$' > ucsf-files
```

In addition to the file created by them, some of them have been renamed, merged into others, or renamed.  This was limited to code in `devices/`.  For example, `mover.py` was split into `dummyXYStage.py` and `dummyZStage.py`.  Also, originally there were multiple devices directories, one per system and we had two `devices-ucsf*`.  The following list was manually curated:

```
cat >> ucsf-files <<END
devices/camera.py
devices/configurator.py
devices/device.py
devices/drawer.py
devices/dummyCamera.py
devices/dummyLights.py
devices/dummyXYStage.py
devices/dummyZStage.py
devices/executorDevices.py
devices/imager.py
devices/__init__.py
devices/nanomover.py
devices/objective.py
devices/physikInstrumenteM687.py
devices/picomotor.py
devices/server.py
END
```

Then resort the list of files, remove duplicates, and filter out files that no longer exist:

```
comm -1 -2 all-files <(sort -u ucsf-files) > ucsf-files.tmp
mv ucsf-files.tmp ucsf-files
```

## List contributions not from UCSF

```
git log --no-merges \
  --author="map" \
  --author="Mick" \
  --author="mickp" \
  --author="Mick Phillips" \
  --author="unknown" \
  --name-only --pretty=format:"" | sort -u | grep -P '\.pyw?$' > mick-files
git log --no-merges \
  --author="Carnë Draug" \
  --author="David Pinto" \
  --name-only --pretty=format:"" | sort -u | grep -P '\.pyw?$' >  david-files
git log --no-merges \
  --author="Ian Dobbie" \
  --name-only --pretty=format:"" | sort -u | grep -P '\.pyw?$' >  ian-files
git log --no-merges \
  --author="Julio Mateos Langerak" \
  --name-only --pretty=format:"" | sort -u | grep -P '\.pyw?$' >  julio-files
git log --no-merges \
  --author="langefj" \
  --name-only --pretty=format:"" | sort -u | grep -P '\.pyw?$' >  rick-files
git log --no-merges \
  --author="NickHall" \
  --name-only --pretty=format:"" | sort -u | grep -P '\.pyw?$' >  nick-files
git log --no-merges \
  --author="Thomas Parks" \
  --author="tomparks" \
  --name-only --pretty=format:"" | sort -u | grep -P '\.pyw?$' >  tom-files

rm -f gpl-files
for AUTHOR in mick david ian julio rick nick tom ; do
  comm -1 -2 all-files $AUTHOR-files > $AUTHOR-files.tmp
  mv $AUTHOR-files.tmp $AUTHOR-files
  cat $AUTHOR-files >> gpl-files
done
sort -u gpl-files > gpl-files.tmp
mv gpl-files.tmp gpl-files
```

## Adding the copyright notice

Remove the shebang line from cockpit.pyw so we can simply prepend the license header.  Some add the shebang and coding line. We'll add them again at the end:

```
shebang_files="cockpit.pyw"
shebang_coding_files="devices/boulderSLM.py devices/dummyAnalog.py devices/light.py devices/microscopeCamera.py devices/microscopeDevice.py devices/polarizationRotator.py devices/softCamera.py util/intensity.py"

for FPATH in $shebang_files ; do
  tail -n +2 $FPATH > $FPATH.tmp
  mv $FPATH.tmp $FPATH
done
for FPATH in $shebang_coding_files ; do
  tail -n +3 $FPATH > $FPATH.tmp
  mv $FPATH.tmp $FPATH
done
```

Prepared the different headers for the different licenses with trailing empty lines and append to the right files:

```
while read FPATH; do
  cat COPYING.BSD-3-clause-header "$FPATH" > "$FPATH.tmp"
  mv "$FPATH.tmp" "$FPATH"
done < <(comm -2 -3 ucsf-files gpl-files)

while read FPATH; do
  cat COPYING.GPL-header "$FPATH" > "$FPATH.tmp"
  mv "$FPATH.tmp" "$FPATH"
done < <(comm -1 -3 ucsf-files gpl-files)

while read FPATH; do
  cat COPYING.both-header "$FPATH" > "$FPATH.tmp"
  mv "$FPATH.tmp" "$FPATH"
done < <(comm -1 -2 ucsf-files gpl-files)
```

And put the correct copyright holders:

```
mick="Mick Phillips <mick.phillips@gmail.com>"
david="David Pinto <david.pinto@bioch.ox.ac.uk>"
ian="Ian Dobbie <ian.dobbie@bioch.ox.ac.uk>"
julio="Julio Mateos Langerak <julio.mateos-langerak@igh.cnrs.fr>"
rick="Frederik Lange <frederik.lange@dtc.ox.ac.uk>"
nick="Nicholas Hall <nicholas.hall@dtc.ox.ac.uk>"
tom="Thomas Park <thomasparks@outlook.com>"

for AUTHOR in tom rick nick david julio ian mick ; do
  printf "## Copyright (C) 2018 %s\n" "${!AUTHOR}" > copyright-line
  while read FPATH; do
    cat copyright-line "$FPATH" > "$FPATH.tmp"
    mv "$FPATH.tmp" "$FPATH"
  done < $AUTHOR-files
done
```

Put the shebang line and coding lines back in place:

```
for FPATH in $shebang_files $shebang_coding_files ; do
  cat <(printf '#!/usr/bin/env python\n# -*- coding: utf-8 -*-\n\n') $FPATH > $FPATH.tmp
  mv $FPATH.tmp $FPATH
done
```

## Cleanup

* removed the BSD license at the root of the project.  The project is GPL, we only have some files that are also under BSD and those files have the notice as required.
* manually cleaned some files that already had a license header, including Micks Apache 2
* some files only had a line specifying utf-8 coding

**Comment by carandraug** [comment]
See commit bab198f for the changes. I had to open the issue first so I could refer to it on the commit message.

**Comment by iandobbie** [comment]
List of files sounds reasonable and of course I am happy with the licensing as we have been discussing.

**Comment by juliomateoslangerak** [comment]
Hi, I'm happy with the list and the licensing.

J.

**Comment by iandobbie** [comment]
Is this not now all done and able to be closed?

**Comment by carandraug** [comment]
> Is this not now all done and able to be closed?

Kind of. Not really necessary, but would be nice if the people involved would thumbs up this. It's missing @tomparks, @langefj, @NickHallONBI and @mickp

**Comment by mickp** [comment]
Sorry - we discussed this over e-mail and in person, but I never posted anything here. 
👍

**Comment by tomparks** [comment]
lgtm, thumbs up from me.

Thanks,
Tom

On 13 Jul 2018, at 16:20, Mick <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry - we discussed this over e-mail and in person, but I never posted anything here.
👍

**Comment by NickHallONBI** [comment]
Hi 

Sorry, I had discussed this with a number of people in person but never officially posted here. Yes, I'm happy that those files are the ones I've worked on and with the form of my name and email.

Cheers

Nick

**Comment by langefj** [comment]
Hi,

Happy with all as is.

Cheers,
Rick

**Comment by iandobbie** [comment]
Ok, I think that is everybody. Can we c lose this issue now?
