### ISSUE TITLE
MacOS touchscreen not working

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#315]
Running Cockpit on MacOS complains about the touchscreen. Commenting out on cockpit/__init__
these two lines (175 and 176) solves the problem
            # import cockpit.gui.touchscreen.touchscreen
            # cockpit.gui.touchscreen.touchscreen.makeWindow(frame)

J

**Comment by iandobbie** [comment]
Ok. I’ll see what is broken in the touchscreen and fix it!

Ian

Sent from my iPhone

On 2 Jul 2018, at 15:38, juliomateoslangerak <notifications@github.com<mailto:notifications@github.com>> wrote:


Running Cockpit on MacOS complains about the touchscreen. Commenting out on cockpit/init
these two lines (175 and 176) solves the problem
# import cockpit.gui.touchscreen.touchscreen
# cockpit.gui.touchscreen.touchscreen.makeWindow(frame)

J

**Comment by iandobbie** [comment]
fixed in #331
