### ISSUE TITLE
Linux: close/kill button doesn't work

### ISSUE THREAD

**Issue by mickp** [MicronOxford/cockpit#348]
Looked at this with wx.lib.inspection.InspectionTool. It seems that the EVT_CLOSE event is never fired.

**Comment by mickp** [comment]
In CockpitApp.OnInit, the line
`cockpit.util.user.login(frame)`
makes wx jump into the main loop, before app.MainLoop has been called.
If I comment out this line, then the EVT_CLOSE event is fired correctly - everything closes, except the logging window.
The user login stuff should be called *after* OnInit has completed, and probably after app.MainLoop has been called. Perhaps wx.CallAfter will work?

**Comment by mickp** [comment]
CallAfter works, and had to fix typo that meant a daemon thread wasn't a daemon. Close button now works, but there's a segfault on exit.

**Comment by iandobbie** [comment]
This also fixes the not closing python issue on macos, however it also segfaults at the end.
