### ISSUE TITLE
Touchscreen site marking doesn't work

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#360]
The touchscreen site selection function now generates an error. Go somewhere and right click to select a site. 

File “/Users/ian/src/cockpit/cockpit/gui/touchscreen/touchscreen.py”, line 700, in <lambda>
    lambda event, color = color: self.saveSite(color))
AttributeError: ‘TouchScreenWindow’ object has no attribute ‘saveSite’

Also several deprecation warnings.

**Comment by mickp** [comment]
My mistake - I pulled out all the site code because the touchscreen had no site buttons, and it looked like it was hanging around from when code was copied from the mosaic window.
Fixed in 904d6800b7ee25743f1f57431008947f8d6.
