### ISSUE TITLE
A possible problem with image counter on large experiments. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#365]
Reportedly the image counter reached 2048 an d 2047 in a large 2 channel SIM experiment and then froze. This happened repeatedly at the same values. The experiment continued and completed successfully but we should test extremly large SIM stacks and see if they work properly. 

Ian

**Comment by mickp** [comment]
If the experiment completed successfully, I wouldn't worry about the status
display: there's nothing to guarantee it gets updated and, indeed, if the
cockpit process is busy doing I/O, the UI may not be updated for some time.
I think the only way to fix this is to have I/O and UI in separate
processes.
