### ISSUE TITLE
Movement step sizes need some work. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#413]
There are a range of issues:

- [ ] XY and Z step sizes are linked and at a mad level. 

- [x] When the piezo stage is selected on deepsim you cannot move xy

- [ ] The piezo step sizes are a bit mad too 1.25, 2.5,12.5. I think we need at least a 5.

**Comment by iandobbie** [comment]
point 2 fixed in #415

**Comment by NickHallONBI** [comment]
Tested on DeepSIM and it doesn't appear to break anything.

**Comment by carandraug** [comment]
I have pushed 18baf6b which Nick just tested.  This fixes point 2 of this issue.

**Comment by mickp** [comment]
Nope.  Commit 18baf6bc6439bbc1e4ea10c2fd74a5c completely breaks mosaic and macrostage: the stage is twice as large as it should be, moves move twice the distance that they should, and the mosaic is just plain weird.

Reverting.

![image](https://user-images.githubusercontent.com/5138863/48771224-b0413080-ecb8-11e8-9476-deb2eb906da5.png)

**Comment by carandraug** [comment]
Can someone now test my branch carandraug/cockpit@98f48250ad51b3577afa7448dd7282db939c1263 (branch refix-stagemover-413)

This ensures that we don't pick duplicated handlers when computing stage limits (adds all stages together) and movement sizes (also uses the non-used stages to compute offset).

**Comment by carandraug** [comment]
@mickp tested this and approved. Reverted the reversion, rebased the fix, squashed, and pushed. This re-closes point 2 of this issue.

**Comment by iandobbie** [comment]
This is a solved issue so closing
