### ISSUE TITLE
sr470 goes to sleep

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#424]
When the 561 line is activated then deactivated the shutter controller goes to sleep at Diamond. I have no idea why.

**Comment by mickp** [comment]
Can't reproduce this at Micron: the SR470 works as planned, here. The shutter controller is brought out of sleep mode whenever the laser is enabled. 

I think there may be a fault with the shutter head at Diamond that prevents the controller from waking.

Power cycle the controller with the [Reset] key pressed. See if the behaviour persists.

Is the 'FAULT' light on the SR470 illuminated when you try to re-enable the laser? If so, there's a
problem with the shutter head, its power/control cable, or the 12V supply from the controller.

As a last resort, we could lose the
  self.send("ENAB 0")
from line 82 of sr470.py, but then the shutter might open unexpectedly when the DSP is initialised on
startup or the DSP machine reboots; this could be a safety problem if the laser had been left on.

**Comment by iandobbie** [comment]
Managed to fix with this hack in devices/shutter.py

   def onLightSourceEnable(self, handler, enab):
        if enab and handler in self.lights:
            # One of our lights has been enabled.  Make sure that we respond to triggers.
            self.enableTrigger()
        elif not enab and not any([l.getIsEnabled() for l in self.lights]):
            # All of our lights are disabled.
        #    self.enableTrigger(False)
            pass

**Comment by mickp** [comment]
That's equivalent to losing the "ENAB 0" command I mentioned above, and leaves the shutter responsive to spurious triggers from the DSP. Probably better to fix this in the sr470 device file, because then it only affects the shutter type that has the problem.

**Comment by mickp** [comment]
Did we ever get to the bottom of this? I think we've only ever seen this behaviour at Diamond.

**Comment by iandobbie** [comment]
Nope, not properly investigated. Fixed by a hack of removing the disable call.

**Comment by iandobbie** [comment]
Diamond have ordered a new shutter controller on the assumption that this is a controller issue, especially as it was becoming unresponsive increasingly often. Will update once we can access the lab and test.

**Comment by carandraug** [comment]
To be specific, the patch mentioned above by @iandobbie and was found to fix the issue, has not been pushed.

**Comment by mickp** [comment]
Note the safety-related issue this patch may introduce (see comment dated 2018-11-23).

**Comment by iandobbie** [comment]
We believe that this was due to hardware issues on the Diamond system. We have replaced the controller. I will ask Maria if this appears to be solved or not.

**Comment by iandobbie** [comment]
I understand this is now solved and I am just going to close the issue
