### ISSUE TITLE
setHistogram menu bug

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#435]
gui/imageViewer/viewCanvas.py bugs when I try to change the histogram parameters using the right click contextual menu.
The issue being in lines 585 and 589 where a map object is being subscripted.
Replacing the mapping of the values in line 582 by a comprehension does the trick

`        values = [float(v) for v in values]
`

**Comment by juliomateoslangerak** [comment]
I actually added a 
`        divisor = max(divisor, 1.0)
`
to avoid a zero division error too

**Comment by mickp** [comment]
Yep:
 * List comprehension makes sense, since values[] is short.
 * A lower bound on divisor is sensible.

**Comment by iandobbie** [comment]
These two issues are fixed in my branch histMenu, can someone check I haven't done anything mad.

**Comment by carandraug** [comment]
For future reference, what happens when changing histogram parameters is the following error is thrown:

```
Traceback (most recent call last):
  File "/home/carandraug/src/cockpit/cockpit/gui/imageViewer/viewCanvas.py", line 559, in <lambda>
    self.Bind(wx.EVT_MENU,  lambda event, action = action: action(), id= id)
  File "/home/carandraug/src/cockpit/cockpit/gui/imageViewer/viewCanvas.py", line 588, in onSetHistogram
    self.blackPoint = (values[0] - self.imageMin) / divisor
TypeError: 'map' object is not subscriptable
```

**Comment by mickp** [comment]
It's a python 2-3 thing, I think. Iterating over the result of a map() call
will work in python 2, but it needs converting into an iterable in python 3.

**Comment by carandraug** [comment]
Now pushed to master.
