### ISSUE TITLE
Lost option to do pseudoglobal exposure mode

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#441]
Hi,
I think the option to do pseudoglobal exposure (TRIGGER_DURATION_PSEUDOGLOBAL) is lost in the microscopeCamera. 
Is that right?

**Comment by mickp** [comment]
microscopeCameras do not currently support TRIGGER_DURATION_PSEUDOGLOBAL. I don't recall seeing a working camera device/remote pair that supported this.

**Comment by juliomateoslangerak** [comment]
I believe this is fixed through the experiment design. Indeed that is not a feature of the camera
