### ISSUE TITLE
cockpit font

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#443]
We are currently using the Universalis font by Arkandis Digital Foundry (ADF) in the openGL canvas.

I just read about the B612 font which is also under a free software license (Eclipse Public License) but was designed on purpose for use on aeronautical cockpit screens. I just thought it might be quite suitable to use in our own cockpit. http://b612-font.com/

**Comment by mickp** [comment]
Nice idea. I just tried it out in an editor. I'm not sure that they're a problem for our UI, but here are a few observations:
* The parentheses look very much like square brackets in other typefaces.
* The O (uppercase 'o') and 0 (zero) are very similar.

![image](https://user-images.githubusercontent.com/5138863/51478302-01d26e00-1d83-11e9-8a6d-632eb3cd32ef.png)

**Comment by iandobbie** [comment]
I thought this was cool, I don't think the bracket issue is a problem but 0O confusion might be. 

Thoughts?

**Comment by iandobbie** [comment]
I guess as nothing has moved forward on this in a year or so we should just close this.
