### ISSUE TITLE
Camera view canvas zoom assumes 512x512

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#459]
Using the scroll wheel of the mouse to zoom on the camera view works well with 512x512 images but not with bigger sizes (didn't test smaller sizes). The image zooma but gets out of scope.

**Comment by iandobbie** [comment]
Yes. There is also a problem with the alignment crosshairs which plots them in the wrong position.  Needs to be fixed

Sent from my iPhone

On 15 Feb 2019, at 10:50, juliomateoslangerak <notifications@github.com<mailto:notifications@github.com>> wrote:


Using the scroll wheel of the mouse to zoom on the camera view works well with 512x512 images but not with bigger sizes (didn't test smaller sizes). The image zooma but gets out of scope.
