### ISSUE TITLE
support non-square images

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#463]
Acquired images may not be square but cockpit won't work with them. For example, ur new IDS cameras have a sensor size of 1936x1216.

**Comment by carandraug** [comment]
The new binning in microscope allows for different vertical and horizontal binning. That not only enables non square images, it also creates images with different pixel sizes on each dimension.

**Comment by iandobbie** [comment]
I have a similar problem with the picam. The mosaic actually deals with them, but the camera view canvas does mad things see #493

**Comment by iandobbie** [comment]
I think this now works, There is a small issue in mosaic but it is minor and probably needs another issue opened for it anyway
