### ISSUE TITLE
nicer window display for exceptions

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#467]
If there is an exception initialising cockpit, the traceback is show in a StaticText widget, with"normal" font family, and text wrapping.  The problem of static text is that we can't select the text to copy and paste somewhere else (future user googling for users, or grepping the code). The non monospaced text and text wrapping makes the traceback more difficult to follow.  Currently, it looks like this:

![current](https://user-images.githubusercontent.com/916140/55569661-de6c5d80-56f9-11e9-9e98-8ee41eecba37.png)

As part of another work, I wrote a simple function to display an exception traceback. It looks like this:

![no-details-to-expand](https://user-images.githubusercontent.com/916140/55569775-107dbf80-56fa-11e9-8efd-4bfb47c7cbbd.png)

There is also a version where the traceback is in a collapsible pane (collapsing/uncollapsing can be done via keyboard with Tab + Space):

![collapsed](https://user-images.githubusercontent.com/916140/55569897-47ec6c00-56fa-11e9-8f40-bef7d401682c.png)
![not-collapsed](https://user-images.githubusercontent.com/916140/55569898-48850280-56fa-11e9-9a65-14308c1e9f23.png)

This is a function meant to be used wherever in the cockpit gui when an exception occurs. At the moment, the only place is during initialisation. On the work I have done for experiment panel, I also use when an experiment fails during initialisation.

I have an `exception-box` on my clone.  Or see the commit at https://github.com/carandraug/cockpit/commit/cbf384528ab1f32caedeea03165a338d758f01ed

**Comment by iandobbie** [comment]
Seems like a no brainer. The current dialog is almost useless, very difficult to read, and not being able to copy and paste is a continual annoyance to me.

**Comment by carandraug** [comment]
I have proposed two different versions, it's not clear which one you guys prefer.

I will push the one without collapsible pane. Its code is simpler and I've found that the traceback is often needed to interpret the error message. Might as well have it displayed by default. A collapsible pane only makes sense if by default is collapsed.

**Comment by carandraug** [comment]
Pushed the changes. I have pushed two commits so that if we ever want to have the traceback by default, it's already in the git history.
