### ISSUE TITLE
Unused parameter in shellWindow makeWindow

### ISSUE THREAD

**Issue by mickp** [MicronOxford/cockpit#474]
Should we then just remove the `parent` argument from this function? It was only used here.

_Originally posted by @carandraug in 
https://github.com/MicronOxford/cockpit/pull/447#discussion_r251452099

**Comment by carandraug** [comment]
The `parent` argument is now used by `shellWindow`. It seems the reason why it did not accept it was the way the main window handled keyboard events. That has been fixed, so `shellWindow` could now be a child of the main window. See more details on the commit message that did it 5c5dabdd328694e5507646e1762eb961b85e377d
