### ISSUE TITLE
Mosaic deals fine with rectangular images but the viewcanvas doesn't

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#493]
The picam returns at 720x480 image. Teh mosaic tiles these in the correct place and seems to move the right amount (in simulated stage mode anyway). However, the main camera view window just doesn't cope with rectangular image and squashes it to square on the display

**Comment by iandobbie** [comment]
I looked at the code but it is pretty deep GL stuff. I think it is mapping the pixels over the square viewport, no matter hjow many their are in each direction, but I didn't get to the bottom of it.

**Comment by carandraug** [comment]
I'm having the same issue now with the IDS cameras. The sensor size is rectangular (1936x1216), the camera view is square, so the pixels on the camera view end up rectangular.

**Comment by mickp** [comment]
I fixed this on the camera by adjusting the quad co-ordinates. While mosaic looks like it's dealing with non-square images, I think it's doing it incorrectly: it looks like it's scaling the pixels along the wrong axis.
![image](https://user-images.githubusercontent.com/5138863/57870231-96634f00-77fe-11e9-883e-a673b1f7e051.png)

**Comment by mickp** [comment]
#499 will fix this.

**Comment by iandobbie** [comment]
This is fixed so closing
