### ISSUE TITLE
StageMover - do not move coarse Z at start of experiment

### ISSUE THREAD

**Issue by mickp** [MicronOxford/cockpit#5]
Check that the requested range is addressable by the fine stage in the current position.  If not, tell the user / ask them if we should move the coarse stage.

**Comment by mickp** [comment]
Not sure of the state of this. Used to be that at the start of any experiment, the code would deliberately make moves with outer movers to centre the inntermost mover. This is not desirable, because outer positioners may have much lower accuracy and reproducibility.  Test what the case is now on DeepSIM.

**Comment by iandobbie** [comment]
The current code will not start and experiment unless we are on the finest Z mover. This by definition has the smallest range of motion and is assumed to be the most accurate. This will fail if you try to move further than the movement range of the fine motion, so solves the issue
