### ISSUE TITLE
Add easy way to clear experiment altitude histogram

### ISSUE THREAD

**Issue by mickp** [MicronOxford/cockpit#501]
MacroStage Z populates the Z scale with a histogram of former experiment positions, which are stored in the user config file as experimentAltitudes. We should add an easy way to clear this, e.g. via a context menu. Diamond now has a manual coarse Z stage, so any movement of that invalidates the histogram, as might changing the sample mounting on any other system.

**Comment by iandobbie** [comment]
The Edit/Reset user configuration clears this data and so I am closing this as solved as a side effect of the addition of that functionality.
