### ISSUE TITLE
Button text is not readable under OS-X dark themes

### ISSUE THREAD

**Issue by mickp** [MicronOxford/cockpit#520]
With a dark theme under OS-X, the windows and buttons are drawn using colours from the light theme, but their labels are rendered with a colour from the dark theme - the result is light text on a light background.

This is odd, because we're using native buttons, and they work fine for dark themes under GTK. Perhaps wxWidgets' SYS_COLOUR entires haven't yet caught up with the recently-introduced theming?

**Comment by iandobbie** [comment]
I suspect that somewhere along the way apple/wx have fixed this as my current system macos 11.6 doesnt have this problem. 

I have also created an issue for generalised macos dark mode issues #782

Closing
