### ISSUE TITLE
Deploy for Kseniya

### ISSUE THREAD

**Issue by mickp** [MicronOxford/cockpit#527]
Kseniya is interested in deploying microscope and cockpit. This comment will contain the specification - I'll edit it as I obtain further details.

  camera:  Zyla 5.5
  stage:  ?
  light source: ?

**Comment by mickp** [comment]
Windows installation tool created at mickp/cockpit-windows-installation
Waiting for feedback from Kseniya.

**Comment by mickp** [comment]
Kseniya tried the install script. There was an issue with the URLs I'd used being unsuitable for anonymous cloning. I've fixed those, but now she has a problem with the script terminating almost immediately. I suspect it's a access control issue - the script needs to be run as Administrator by an account with admin privileges - but she's running Windows 10, and I've only tested on Windows 7.

**Comment by iandobbie** [comment]
We tested this on windows 10 twice with the DPhil students this week and it worked very well. Only issue I found was once the system is installed as admin you then need the use the admin account to get a develop source tree to work. Overall a major success so I am closing.
