### ISSUE TITLE
OpenGL errors on Nvidia GTX 1080

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#540]
The Aurox computer has an Nvidia GTX 1080 and the mosaic tile update generates an openGL error 1286, seems to be an invalid frame buffer error from google search. I was rushing home but I will get a proper error message tomorrow.

**Comment by iandobbie** [comment]
Reducing the max tile size by 16 fixes this issue so the graphics card is reporting more texture memory than it can actually access. Maybe we should limit to some set value (16385x16385?)

**Comment by mickp** [comment]
As we discussed, it can address the memory, but it can't create a frame
buffer of that size. We need a sensible upper limit on tile size. 16384
will probably do it.

**Comment by iandobbie** [comment]
Ok, I will try to do something like min(returned size, 16834) and see how it works on the Apple and GTX1080 cards which caused problems.

**Comment by mickp** [comment]
Fixed by #550 ... I didn't see #546 until after I merged.
