### ISSUE TITLE
make mosaic window optional

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#547]
Discussing at SPAOM2019, two groups wanted to use it for lightsheet microscope. In here, the mosaic window does not make a lot of sense, so maybe we could make it optional and have alternative windows to move sample.

**Comment by iandobbie** [comment]
1) I don't see why the mosaic make sense in light sheet?  I guess they think rotation makes the mosaic irrelevant sometimes?

2) you can already navigate with keyboard or by double clicking in the macrostage
