### ISSUE TITLE
remove the ability to not draw primitives

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#609]
On the code comments about a needed refactor of `MosaicCommon` I found the following entry from 3b536658bc08:

```
    #   eliminate self.drawPrimitives - they're useful for navigation and don't add much clutter.
```

I can easily remove this if no one opposes and I guess it will make any future refactor simpler.

**Comment by carandraug** [comment]
Proposed code to remove this on my `609-remove-no-draw-primitives` branch.

**Comment by iandobbie** [comment]
I don't quite understand. Are you just removing to ability to turn the primitives on and off?

**Comment by carandraug** [comment]
> I don't quite understand. Are you just removing to ability to turn the primitives on and off?

Yes. There was an old comment from @mickp on the code proposing that (the comment mentioned above), so here's the code to actually do it.

**Comment by iandobbie** [comment]
Ok, just needed to make sure you weren't removing them all together as they are very useful.

**Comment by carandraug** [comment]
I have now pushed fcdd47fd3158 . Closing as fixed.
