### ISSUE TITLE
The new window arrangement has totally killed the macos version.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#622]
The master branch is totally broken on mac and unusable. Can we please roll back the changes until this is fixed.

**Comment by carandraug** [comment]
Of course, we can rollback anything. But can you give more details on what exactly is making it "totally broken and unusable"? There's been a lot of changes in the last few months, the only one I know of that is that important is the already reported #618 .

**Comment by iandobbie** [comment]
Sorry I was having a bad day. Of course this is issue #618 and Danny's suggested fix works on Mac and, I believe, windows as Danny is on windows.
