### ISSUE TITLE
No freetype module. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#630]
Just updated with git pull upstream master 
  2c298a6c..73a62a11  master     -> upstream/master

And I get the error 

File "/Users/ian/src/cockpit/cockpit/gui/imageViewer/viewCanvas.py", line 57, in <module>
    import cockpit.gui.freetype
ModuleNotFoundError: No module named 'cockpit.gui.freetype'
.
So I think the freetype.py file is missing in master

**Comment by carandraug** [comment]
Ups. I forgot to add the module. Now fixed with da1771b4779b0d7ea8.
