### ISSUE TITLE
channel configurations are not validated

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#633]
This come about on the discussion of issue #597 which is what validation should we do when loading channel files (the files loaded via the menu bar "Channels > Import channels ...":

> I'm wondering if we should be doing some validation of the loaded files.
>
> 1. if we load a file that tries to set devices that do not currently, should we error?
> 2. and the opposite, if we load a file that does not include devices that do exist, should we error?
>
> I think we should error in both cases above since the config file is obviously not adjusted to the current setup and we may end up setting everything incorrectly. @iandobbie and @juliomateoslangerak what do you think?

**Comment by iandobbie** [comment]
I think if the config has a device which doesn't exist this should definitely throw and error. However I can see that adding a single device would then generate errors from everyones configs. How about just a warning in this situation.

**Comment by iandobbie** [comment]
So I am suggesting
1) gives and error 
2) gives a warning

**Comment by carandraug** [comment]
Done as @iandobbie suggested with bcc2825 . Closing as fixed.
