### ISSUE TITLE
display fraction of laser power instead of "fake" power

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#641]
On the panel for light sources in the main window, we display laser power in mw.  However, this is meant to be the laser power being emitted and is not the power that reaches the sample which is what the user really cares about.

We probably should be using a percentage of laser power.

**Comment by carandraug** [comment]
I have a proposal on my "wip-641-laser-fractions" branch. It will require the changes, not yet merged, in MicronOxford/microscope#155 .

**Comment by juliomateoslangerak** [comment]
I agree with this. Also, the user does not care about laser power.

**Comment by carandraug** [comment]
I pushed the proposed changes with 01245ab
