### ISSUE TITLE
Multisite experiment not working

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#656]
When sites are selected, the multisite experiment breaks:

It seems to try to get positions calling 'getAllSites', that returns a dict_values object. This one is later on (enumerateSitesPanel.py line 93) failing to be indexed.
This can be solved by wrapping the return of the call into a list in line 89

**Comment by carandraug** [comment]
Thank you for the fix. I pushed your suggestion and it's working again.
