### ISSUE TITLE
Freetype doesn't work on Windows 10

### ISSUE THREAD

**Issue by NickHallONBI** [MicronOxford/cockpit#657]
freetype-py.2.2.0 for Python 3.7 is automatically installed when installing cockpit. However, the "import freetype" line in cockpit/gui/freetype.py fails with the following traceback:

>  Traceback (most recent call last):
>   File "C:\Python37\lib\site-packages\freetype_py-2.2.0-py3.7-win-amd64.egg\freetype\raw.py", line 49, in <module>
>     _lib = ctypes.CDLL(filename)
>   File "C:\Python37\lib\ctypes\__init__.py", line 356, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] The specified module could not be found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Python37\Scripts\cockpit-script.pyw", line 11, in <module>
>     load_entry_point('microscope-cockpit', 'gui_scripts', 'cockpit')()
>   File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
>     return ep.load()
>   File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
>     return self.resolve()
>   File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "c:\cockpit\nick\cockpit\cockpit\__init__.py", line 80, in <module>
>     import cockpit.gui.mainWindow
>   File "c:\cockpit\nick\cockpit\cockpit\gui\mainWindow.py", line 72, in <module>
>     import cockpit.gui.fileViewerWindow
>   File "c:\cockpit\nick\cockpit\cockpit\gui\fileViewerWindow.py", line 53, in <module>
>     from cockpit.gui import imageSequenceViewer
>   File "c:\cockpit\nick\cockpit\cockpit\gui\imageSequenceViewer.py", line 54, in <module>
>     import cockpit.gui.imageViewer.viewCanvas
>   File "c:\cockpit\nick\cockpit\cockpit\gui\imageViewer\viewCanvas.py", line 57, in <module>
>     import cockpit.gui.freetype
>   File "c:\cockpit\nick\cockpit\cockpit\gui\freetype.py", line 57, in <module>
>     import freetype
>   File "C:\Python37\lib\site-packages\freetype_py-2.2.0-py3.7-win-amd64.egg\freetype\__init__.py", line 24, in <module>
>     from freetype.raw import *
>   File "C:\Python37\lib\site-packages\freetype_py-2.2.0-py3.7-win-amd64.egg\freetype\raw.py", line 52, in <module>
>     raise RuntimeError('Freetype library not found')
> RuntimeError: Freetype library not found

>     raise RuntimeError('Freetype library not found')
> RuntimeError: Freetype library not found

**Comment by carandraug** [comment]
I would guess that this is an issue on freetype but I'm surprised because it's supposed to come with the dll. If you start a python shell (no pycharm), and just do `import freetype` does it work? If not, you should report this to https://github.com/rougier/freetype-py

**Comment by NickHallONBI** [comment]
I get much the same error when importing it in a Python shell. I have raised an issue on the freetype GitHub

**Comment by carandraug** [comment]
For reference, the issue opened with freetype-py is rougier/freetype-py/#126 . Closing this.
