### ISSUE TITLE
Sites list does not parse

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#662]
Multisite experiment will not start because sites string cannot be parsed. 
The problem is actually that the code tries to get the length of a filter object. 

I have a fix in this PR  https://github.com/MicronOxford/cockpit/pull/661/commits/d67785b2d013d4a551c095487c25ebeceef871c9 where I replace the filter with a comprehension. As in order to get the length of the filter we need to wrap it into a list, that totally defeats the purpose of the filter.

**Comment by carandraug** [comment]
Thank you for the fix. I have pushed your fix after amending the commit message to point to this issue.
