### ISSUE TITLE
Filter panel disappears when large amount of cameras are used

### ISSUE THREAD

**Issue by dstoychev** [MicronOxford/cockpit#671]
It's okay with a handful but when I use 9 cameras the filters panel doesn't show any more. Here is an example:

![cockpit](https://user-images.githubusercontent.com/56877735/90788519-ccdf2200-e2fd-11ea-9ec7-667a22d51e53.png)

**Comment by carandraug** [comment]
Trying to reproduce the problem, if the "Cameras" subpanel is wide enough that the "Filters" subpanel does not fit (requires the window to get wider), the "Filters" subpanel disappears.

The layout of the main window is as follow:

    +---------------------------------+
    |        Top row buttons          |
    +---------------------------------+
    | WrapSizer for non-light devices |
    +---------------------------------+
    |         Light devices           |
    +---------------------------------+

Note that the mid section is a `WrapSizer` meaning that if its items don't all fit in one row, a second row should appear.  The "Filters" panel is being moved to a second row but for some reason that second is not displayed (looks like the panel with the `WrapSizer` is not being expanded vertically).  I'm not sure if this `WrapSizer` ever worked (the change comes from ff96e9f8e4ea but I can't run cockpit from back then with microscope dummy cameras).

I tried to fix it but I can't find the root issue.  The whole organisation of the main panel is a bit odd.  I ended up restructuring the MainWindowPanel and suddenly seems to work but I'm not sure why it works now and it didn't before.
