### ISSUE TITLE
microscopeDeformableMirror assumes a square image for wavefront sensor. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#679]
The microscopeDeformabelMirror composite device including a DM and an intereferometer for wavefront sensing assumes that the camera on the interferometer is square.

Can be worked around by setting a square ROI on the camera

**Comment by carandraug** [comment]
None of of the deformable mirror stuff has been merged yet. Adding @NickHallONBI which I guess is the author of code one some of his branches.

**Comment by NickHallONBI** [comment]
This is a Microscope-AOtools issue, not a cockpit issue. I will add it to the Microscope-AOtools project

**Comment by carandraug** [comment]
This is a link to the issue opened MicronOxford/microscope-aotools#5 (by the way, Nick, it's possible to transfer issues between repositories, see the "Transfer issue" button at the bottom of the right side bar).
