### ISSUE TITLE
userConfig saves everything on cockpit exit

### ISSUE THREAD

**Issue by mickp** [MicronOxford/cockpit#69]
So the value logger 'save' menu entry is pointless - whatever you save using this option will get overwritten by whatever you were showing when cockpit exits.
Should either
- remove the menu entry (easy)
- make a class of userConfig entries that are only saved when explicitly requested (probably considerable work, and I don't know if there's anywhere else this would be useful)

**Comment by iandobbie** [comment]
Just found another issue with this right click menu

 File “/Users/ian/src/cockpit/cockpit/gui/valueLogger.py”, line 124, in onRightMouse
    menu.Append(i, ‘Save to user config.’)
wx._core.wxAssertionError: C++ assertion “id != 0 || pSubMenu != NULL” failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py37/Phoenix/ext/wxWidgets/src/osx/menuitem_osx.cpp(39) in wxMenuItem(): A MenuItem ID of Zero does not work under Mac

**Comment by iandobbie** [comment]
as suggested removed menu item and fixed menu issue #385
