### ISSUE TITLE
Setup.py still references a non-existent README file

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#696]
The move of the README to README.rst needs to be reflected in the setup.py file.

**Comment by iandobbie** [comment]
Fixed in my master by just replacing with README.rst, don't know if you want to preprocess the .rst file in some way.

**Comment by carandraug** [comment]
I was about to reply that it was done yesterday, but I noticed now that it's used in a couple of other places (one other place in setup.py and another in doc/index). Fixed now.
