### ISSUE TITLE
Clone/pull failed because of invalid path

### ISSUE THREAD

**Issue by dstoychev** [MicronOxford/cockpit#704]
This may be Windows related, but pulling or cloning fails at the moment. Sample output:

```
$ git clone https://github.com/MicronOxford/cockpit.git
Cloning into 'cockpit'...
remote: Enumerating objects: 195, done.
remote: Counting objects: 100% (195/195), done.
remote: Compressing objects: 100% (133/133), done.
remote: Total 12435 (delta 89), reused 152 (delta 61), pack-reused 12240
Receiving objects: 100% (12435/12435), 14.55 MiB | 742.00 KiB/s, done.
Resolving deltas: 100% (9359/9359), done.
error: invalid path 'aux/convert-images-to-png.py'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

The same `error: invalid path 'aux/convert-images-to-png.py'` is given when I try to pull on a different (Windows) computer.

**Comment by dstoychev** [comment]
Seems like "aux" is a reserved filename under NTFS. It'd be nice to rename the new aux directory. The alternative is for users to set the `core.protectNTFS` Git flag to false.

**Comment by iandobbie** [comment]
Yes but having a file called aux on windows is a bad idea, like COM and PRT. Oh the joys of historical baggage. Just change the dir name.

**Comment by carandraug** [comment]
I was not aware of AUX being a reserved filename. It's just a name I've seen before to store the build auxiliary tools. So I renamed to tools. Closing as fixed.

**Comment by mickp** [comment]
Full list of prohibited names for reference, from https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions

![image](https://user-images.githubusercontent.com/5138863/107097971-f8c66500-67c2-11eb-888d-d3b6a0e447b4.png)

**Comment by iandobbie** [comment]
Reading deeper the windows file name space becomes even more arcane. Check out the  "\\?\" prefix, you can then insert "/./" and "/../" into file paths. The joys!
