### ISSUE TITLE
Dialogue if starting a mosaic with no camera. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#724]
I have a couple of edits, changing the text on the touchscreen error dialogue and adding a similar dialogue to the normal mosaic. in my branch mosaic-errors

**Comment by iandobbie** [comment]
So I have rebased this onto master and push to my repository as 724-mosaic-errors. It is really only about 5 lines of change, can we just merge it?

**Comment by carandraug** [comment]
Rebased, split, and merged. Closing as fixed.
