### ISSUE TITLE
On Zaber system executor debug windows doesnt have "display last experiment"

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#731]
Not sure why but the Zaber system with a red pitaya executor doesnt get the display last experiment button.

**Comment by iandobbie** [comment]
I this this is a coding error that only causes a problem on windows. In handlers/executor.py line 576

            btn = wx.Button(self, label="Display last experiment")

I think this should be 

            btn = wx.Button(panel, label="Display last experiment")

With this change it seems to work on windows and mac, can you test linux?

**Comment by carandraug** [comment]
You're right. I pushed your fix. Closing.
