### ISSUE TITLE
"snapped" images should appear on the mosaic view

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#733]
The point of the mosaic is to create a map of the stage. However, the only images that appear on the mosaic canvas are images acquired via the "run mosaic" option. Images acquired by pressing the "Snap" button on the main window (will that be the most common situation?) do not appear but they can be just as useful to map the stage.

**Comment by iandobbie** [comment]
Yes these images can be useful and there is a keyboard shortcut to transfer them but many images just snapped to find focus or set exposure times/laser power will just corrupt the mosaic so it is a specific design choice not to add the images to the mosaic by default.

Sent from my iPhone

On 12 Mar 2021, at 14:02, David Miguel Susano Pinto ***@***.***> wrote:

﻿

The point of the mosaic is to create a map of the stage. However, the only images that appear on the mosaic canvas are images acquired via the "run mosaic" option. Images acquired by pressing the "Snap" button on the main window (will that be the most common situation?) do not appear but they can be just as useful to map the stage.

**Comment by iandobbie** [comment]
Maybe we need a more transparent method to get the images into the mosaic but I think autoloading all of them is very bad idea from a usability point of view.

**Comment by carandraug** [comment]
> Yes these images can be useful and there is a keyboard shortcut to transfer them [...]

I did not know about this.  I looked into the source code and found that this is the decimal character in the numpad (`.`). This works from the main window and the msoaic window but not the from the camera view window.

**Comment by iandobbie** [comment]
Good point. There are two issues I see here:
1) Another control that has very limited discoverability. I only found it by reading the code and now use it pretty regularly. 
2) We should add the functionality to the camera views, maybe both the keyboard shortcut and maybe add it to the right click menu.

**Comment by iandobbie** [comment]
I am trying to fix up a few issues and this seems like a no brainer. Adding it to the right click menu is very easy and I will do this.

**Comment by iandobbie** [comment]
Added to camera view context menu in 7045e18e283a7dfc4ef11e63379fe98856d18618
