### ISSUE TITLE
can't use ambient light for experiments

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/cockpit#738]
This issue was found with @VroniPfann 

When using ambient light for an experiment, Cockpit complains that there's no executor capable to handle it. To replicate, use this depot file:

```
[camera]
type: cockpit.devices.dummies.DummyCamera

[ambient]
type: cockpit.devices.light.AmbientLight
```

Then try an experiment with that camera and ambient light enabled (in the experiment panel, set the time on the ambient light). The following exception is raised:

```
Exception in thread Experiment-execute:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/carandraug/src/cockpit/cockpit/experiment/experiment.py", line 383, in execute
    raise RuntimeError("Found a line that no executor could handle: %s" % str(self.table.actions[curIndex]))
RuntimeError: Found a line that no executor could handle: (Decimal('0.0'), <light source named Ambient in group ambient>, True)
```

It is possible to run an experiment without any light source by leaving the exposure times empty in the camera/lights panel of the experiment frame. This effectively uses the ambient light. However, this also prevents to set the exposure time on the camera and it's not clear what time is used (I guess whatever was used the last time in the camera).

Current workaround is to set a simple light and assign it an unused line in the executor. Something like:

```
[Ambient]
type: cockpit.devices.light.SimpleLight
triggerSource: the executor
triggerLine: 7
```

**Comment by thomasmfish** [comment]
We're currently working using the changes found in #796
