### ISSUE TITLE
Altitudes are magic numbers

### ISSUE THREAD

**Issue by mickp** [MicronOxford/cockpit#74]
Currently set in devices/configurator.py near line 17.
These should be in global(?) config.

**Comment by mickp** [comment]
After discussions just now:
* keep the altitudes as magic numbers in the config file so they can be set per system;
* keep per-user histogram data, binned before saving (at the moment, experiment heights for all users are just dumped into an ever growing file and binned for display).

**Comment by iandobbie** [comment]
Now in config file.
