### ISSUE TITLE
Experiment use Saved top bottom for a z stack doesnt work.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#741]
The use saved top/bottom appears to do basically the same as current as bottom and doesnt go to the existing saved top/bottom

**Comment by carandraug** [comment]
This was a regression introduced in caebbf9a6a2094. I have just pushed a commit that fixes that regression (reverts one line from the commit that introduced the issue). Closing as fixed (CC'ing @ARCFaria which had mentioned this issue to me in person a couple of days ago so she knows it is now fixed).
