### ISSUE TITLE
Multi-site experiment dialog does not take into account "Customize light frequencies" checkbox

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#756]
The multi-site experiment dialog has a checkbox to opt for customising the lights that are going to be activated for each cycle.
when we check the different options apear. However, the experiment is run using those settings independently of weather the box is checked or not.

**Comment by juliomateoslangerak** [comment]
Is a simple fix
https://github.com/juliomateoslangerak/cockpit/commit/50d93381241a91e3460bf427c40a0a5e44c0f7a1

**Comment by iandobbie** [comment]
Pulled into master
