### ISSUE TITLE
Multisite experiments progress do not print the right cycle nr

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#779]
Indeed the multi-site experiment prints to follow progress take the 0-based cycle index in stead of the more user friendly 1-based.
Also, as the progress is printed as "cycle x out of n", it makes more sense to keep those coherent.

**Comment by juliomateoslangerak** [comment]
Fix in  9bb0ac90946a7cfd0be2f22bfbab472dce63c9a4 and 0061486c178267ec8ae2d4e5a70fef7d46ee7ba0.
I also changed all the prints to f-string formating... if that is the way one day...

**Comment by iandobbie** [comment]
I cherry picked these into the current master.
