### ISSUE TITLE
Set save path in software. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#786]
Diamond have requested an option to set the save file path from within the software interface.

I suggest that it gets added to one of the menu's maybe File or Edit.

**Comment by carandraug** [comment]
There is an option in the experiment dialog now to select the file path. Are they still running an older version of Cockpit?

**Comment by thomasmfish** [comment]
We are. I'm trying to update us at the moment but we're facing some problems with the latest version (I'll be posting those issues). I think this issue can be closed.

**Comment by iandobbie** [comment]
As Tom suggests we are closing as this is part of the current file dialog
