### ISSUE TITLE
Mosaic view breaks when the camera is switched off

### ISSUE THREAD

**Issue by thomasmfish** [MicronOxford/cockpit#787]
At Diamond we are testing the new version of cockpit on a new machine and we've found that the mosaic view completely clears and stops responding if the camera is toggled. I've attached images of the logging panels. The first screenshot is the error upon first toggling the camera, the second is the repeated error we press "Run mosaic" after the initial fault.
![Screenshot 2022-01-10 170113](https://user-images.githubusercontent.com/50103643/148809932-39712785-86ac-4804-b1b7-e0c7a042d508.png)
![Screenshot 2022-01-10 171447](https://user-images.githubusercontent.com/50103643/148809937-914980a9-1a8c-478c-b543-f7a5ffe5f1b1.png)
.

**Comment by thomasmfish** [comment]
I should add I've tried using PyOpenGL 3.1.3b2 (which we have working with our previous version of Cockpit) and 3.1.4 and both have had this issue. PyOpenGL 3.1.5 would not load the mosaic view correctly (there was no location marker), so we weren't able to get as far as this error.

**Comment by iandobbie** [comment]
Obviously this needs some testing but the 1286 error is what we find when the openGL canvas tries to create texture which is too large for the graphics card, also if you create too many textures (ie several thousand on the deepsim, or my mac laptop). What graphics card do you have?

The lack of a location marker is likely similar to several other issues where the mosaic window isn't properly updated. What happens if you move the stage? This often triggers the required redraw. I know this isn't a fix but shows what the fundamental problem is. There are a few places where this is an issue and it is somewhere on my todo list but not an actual issue yet.

**Comment by iandobbie** [comment]
Just for a data point, on my mac in simulation mode (cockpit --no-config-files) disabling the camera makes no difference. If there is no camera enabled the mosaic puts up a modal dialog saying it needs a camera. 

There is something strange happening. Turning on and off a camera sometimes just works, sometimes crashes the mosaic entirely and sometimes just losses some of the tiles. If you zoom out to the required level to get the megatiles the images return. Obviously a bug that is sometimes loosing info but not always.

**Comment by thomasmfish** [comment]
Error 1286 is only when trying to take images after openGL has already broken, even if only ~4 tiles were taken before it broke. It was breaking every time we tried switching the camera off after taking a few mosaic tiles. The new PC has a Nvidia Quadro P2200 5GB graphics card.

I'll need to test again tomorrow to see about moving the stage to update it but Chidinma was clicking on the mosaic view to get it to move and it wasn't responding, though I guess that's not surprising if it wasn't loaded properly.

**Comment by thomasmfish** [comment]
From the meeting, it seems to be an issue relating to the display rescaling the macro tiles after the camera is cleared, so no longer has a min/max.

**Comment by thomasmfish** [comment]
After all of that, it was freetype. Commit acece2390a45b343869fdf7b2b732d504beaf195 was the issue. Simply replacing `glDeleteTextures([self._texture_id])` with `del self` fixed the issue. I'll put a PR in to get a discussion going as to the best way to release the Glyphs

**Comment by thomasmfish** [comment]
Hmm, no my bodge was bad (shocking). I don't know enough about OpenGL to figure this out now but it seems like there should be something fancier going on, [like this](http://bazaar.launchpad.net/~mcfletch/pyopengl-demo/trunk/view/head:/PyOpenGL-Demo/NeHe/lesson43/glFreeType.py).

**Comment by iandobbie** [comment]
> 



> A fun new twist: it doesn't actually remove the tiles! The tiles can still be viewed if zoomed in, but if the mosaic view is zoomed out beyond a certain amount, it disappears. 

This is actually not surprising. There are in fact two sets of tiles, the full resolution ones and a zoomed out version refered to a megaTiles. We are obviously only corrupting one set, however I think it depends on what is being displayed when the camera is disabled as I found the high res tiles being lost rather than mega tiles.

**Comment by thomasmfish** [comment]
Hi Ian, for me I'm pretty sure it was always the megatiles but I haven't tested that properly. Either way, I've put in a PR that seems to fix the issue (I think it was an OpenGL crash due to some textures trying to be deleted twice within too small a time frame (due to them being deleted by different threads).
________________________________

**Comment by thomasmfish** [comment]
@iandobbie I've added a new commit to the branch you pulled that may be more to your liking, though I can't test it on the SIM and could never get the problem to replicate in the simulated system.

I don't understand what is wrong with using linked PRs to suggest changes for issues but I won't do that this time then
