### ISSUE TITLE
Python 3.10 wxWidgets type conversion issues

### ISSUE THREAD

**Issue by dstoychev** [MicronOxford/cockpit#799]
In Python 3.10, built-in and extension functions which take integers as arguments no longer implicitly convert to integer if there will be loss of information, e.g. when converting from a `Decimal` or `float`. This affects wxWidgets in quite a few places and has been fixed since December, but it is only available in the developmental snapshots at the moment: PR #2039 at https://github.com/wxWidgets/Phoenix.

Cockpit has custom widgets which are affected in the same way and require similar treatment. Just by starting a default (no config) Cockpit instance, I have encountered issues in the `MacroStageBase` (built on top of `wx.glcanvas.GLCanvas`) and safe controls (built on top of `wx.Window`). Fixes can be found here: https://github.com/dstoychev/cockpit/tree/python10-fixes.

**Comment by iandobbie** [comment]
This is all explicit casting to int so I have just going to pull it into the main branch.
