### ISSUE TITLE
 WaitMessageDialog is never displayed

### ISSUE THREAD

**Issue by mickp** [MicronOxford/cockpit#8]
WaitMessageDialog subclasses Thread to display a wait dialog in a separate thread.  This doesn't work:  the dialog box needs to be generated in the same thread as all the other wx stuff; trying to generate it in a separate thread means it is never displayed.

Threads are started by calling .start() from your main thread which in turn runs .run() in a new thread.  
If you call .run() directly, it runs in your calling thread. In this case, this means:
- the dialog box is displayed, 
- your main thread is stuck running .run() so can never set shouldStop to False,
- you can not close the dialog box.

Either the dialog box should be created in the main thread then updated via the messaging system, or the code you are waiting for should be forked to a different thread.

**Comment by iandobbie** [comment]
It is also never called from within the code. I suggest we just remove the function. Any objections?

**Comment by mickp** [comment]
It was called, but it was broken as described above: I just took out the call, rather than implement one of the two possible fixes. If it hasn't been missed, we might as well ditch it.

**Comment by carandraug** [comment]
The last uses of `WaitMessageDialog`were removed with 14f5f9f6de2f74f5c5f4c9f (commit that removed the `devices-oxfordOMXT`and `devices-ucsfOMX`) and before that, the only use case was in `devices/andorCameras.py` which got removed in f397139a3cd49fc . That was 3 years ago so I'm guessing that it hasn't been missed. I will remove it.
