### ISSUE TITLE
Cannot start Cockpit due to check

### ISSUE THREAD

**Issue by thomasmfish** [MicronOxford/cockpit#814]
I got the error `'NoneType' object has no attribute 'wavelength'` when starting cockpit due to the check `if self.power.wavelength == None` when `self.power` is `None`. This is from the most recent commit.

I've suggested a PR, since it's a small fix.

**Comment by carandraug** [comment]
Closing as duplicated of issue #700.

**Comment by iandobbie** [comment]
I think this is covered by the fix for #700 and pr #811
