### ISSUE TITLE
Abort button text colour on Mac

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#818]
The Abort button has lost its text colour on more modern Macs. Not sure exactly when it happened but I found a fix today. The current code uses  (gui/mainwindow.py about line 104)

        abortButton.SetLabelMarkup("<span foreground='red'><big><b>ABORT</b></big></span>")

If you replace this with 
        abortButton.SetOwnForegroundColour(wx.RED)

You get the red foreground text colour. Not sure how other systems behave with this.

**Comment by carandraug** [comment]
> If you replace this with abortButton.SetOwnForegroundColour(wx.RED)

Works for me as well. I have pushed 491f22ebc784 which does a slightly different thing to completely remove the need to `SetLabelMarkup`. Closing as fixed.
